--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/archy/github/wallpapers/FlowerField.png"

-- Special
background="#201e1e"
foreground="#c7c6c6"
cursor="#c7c6c6"

-- Colors
color0="#201e1e"
color1="#5F938E"
color2="#84A697"
color3="#ADB091"
color4="#BCBD95"
color5="#DFD0AB"
color6="#EADAB2"
color7="#c7c6c6"
color8="#776262"
color9="#5F938E"
color10="#84A697"
color11="#ADB091"
color12="#BCBD95"
color13="#DFD0AB"
color14="#EADAB2"
color15="#c7c6c6"
