# Shell variables
# Generated by 'wal'
wallpaper="/home/archy/github/wallpapers/FlowerField.png"

# Special
background='#201e1e'
foreground='#c7c6c6'
cursor='#c7c6c6'

# Colors
color0='#201e1e'
color1='#5F938E'
color2='#84A697'
color3='#ADB091'
color4='#BCBD95'
color5='#DFD0AB'
color6='#EADAB2'
color7='#c7c6c6'
color8='#776262'
color9='#5F938E'
color10='#84A697'
color11='#ADB091'
color12='#BCBD95'
color13='#DFD0AB'
color14='#EADAB2'
color15='#c7c6c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
