[colors.primary]
background = "#201e1e"
foreground = "#c7c6c6"

[colors.cursor]
text = "#201e1e"
cursor = "#c7c6c6"

[colors.vi_mode_cursor]
text = "#201e1e"
cursor = "#c7c6c6"

[colors.search.matches]
foreground = "#201e1e"
background = "#c7c6c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#776262"
background = "#c7c6c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#201e1e"
red = "#5F938E"
green = "#84A697"
yellow = "#ADB091"
blue = "#BCBD95"
magenta = "#DFD0AB"
cyan = "#EADAB2"
white = "#c7c6c6"

[colors.bright]
black = "#776262"
red = "#5F938E"
green = "#84A697"
yellow = "#ADB091"
blue = "#BCBD95"
magenta = "#DFD0AB"
cyan = "#EADAB2"
white = "#c7c6c6"

[colors.dim]
black = "#c7c6c6"
red = "#5F938E"
green = "#DFD0AB"
yellow = "#ADB091"
blue = "#BCBD95"
magenta = "#84A697"
cyan = "#EADAB2"
white = "#776262"

