[colors]
background = '#201e1e8e'
black = '#201e1e'
blue = '#5F938E'
cursor = '#c7c6c6'
cyan = '#84A697'
foreground = '#c7c6c6'
green = '#ADB091'
magenta = '#BCBD95'
red = '#DFD0AB'
tabs = '#c7c6c6'
tabs-active = '#EADAB2'
white = '#c7c6c6'
yellow = '#c7c6c6'
dim-black = '#201e1e8e'
dim-blue = '#5F938E8e'
dim-cyan = '#84A6978e'
dim-foreground = '#c7c6c68e'
dim-green = '#ADB0918e'
dim-magenta = '#BCBD958e'
dim-red = '#DFD0AB8e'
dim-white = '#EADAB28e'
dim-yellow = '#c7c6c68e'
light-black = '#5F938E'
light-blue = '#84A697'
light-cyan = '#ADB091'
light-foreground = '#BCBD95'
light-green = '#DFD0AB'
light-magenta = '#EADAB2'
light-red = '#c7c6c6'
light-white = '#5F938E'
light-yellow = '#84A697'
