[colors]
background = '#1213148e'
black = '#121314'
blue = '#8F8B75'
cursor = '#c3c4c4'
cyan = '#A0997E'
foreground = '#c3c4c4'
green = '#A09B83'
magenta = '#B3AB8E'
red = '#C6BB9A'
tabs = '#c3c4c4'
tabs-active = '#D5C8A4'
white = '#c3c4c4'
yellow = '#c3c4c4'
dim-black = '#1213148e'
dim-blue = '#8F8B758e'
dim-cyan = '#A0997E8e'
dim-foreground = '#c3c4c48e'
dim-green = '#A09B838e'
dim-magenta = '#B3AB8E8e'
dim-red = '#C6BB9A8e'
dim-white = '#D5C8A48e'
dim-yellow = '#c3c4c48e'
light-black = '#8F8B75'
light-blue = '#A0997E'
light-cyan = '#A09B83'
light-foreground = '#B3AB8E'
light-green = '#C6BB9A'
light-magenta = '#D5C8A4'
light-red = '#c3c4c4'
light-white = '#8F8B75'
light-yellow = '#A0997E'
