# Shell variables
# Generated by 'wal'
wallpaper="/home/archy/github/wallpapers/GruvboxAnime.png"

# Special
background='#121314'
foreground='#c3c4c4'
cursor='#c3c4c4'

# Colors
color0='#121314'
color1='#8F8B75'
color2='#A0997E'
color3='#A09B83'
color4='#B3AB8E'
color5='#C6BB9A'
color6='#D5C8A4'
color7='#c3c4c4'
color8='#5a646f'
color9='#8F8B75'
color10='#A0997E'
color11='#A09B83'
color12='#B3AB8E'
color13='#C6BB9A'
color14='#D5C8A4'
color15='#c3c4c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
