--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/archy/github/wallpapers/GruvboxAnime.png"

-- Special
background="#121314"
foreground="#c3c4c4"
cursor="#c3c4c4"

-- Colors
color0="#121314"
color1="#8F8B75"
color2="#A0997E"
color3="#A09B83"
color4="#B3AB8E"
color5="#C6BB9A"
color6="#D5C8A4"
color7="#c3c4c4"
color8="#5a646f"
color9="#8F8B75"
color10="#A0997E"
color11="#A09B83"
color12="#B3AB8E"
color13="#C6BB9A"
color14="#D5C8A4"
color15="#c3c4c4"
