[colors.primary]
background = "#121314"
foreground = "#c3c4c4"

[colors.cursor]
text = "#121314"
cursor = "#c3c4c4"

[colors.vi_mode_cursor]
text = "#121314"
cursor = "#c3c4c4"

[colors.search.matches]
foreground = "#121314"
background = "#c3c4c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a646f"
background = "#c3c4c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#121314"
red = "#8F8B75"
green = "#A0997E"
yellow = "#A09B83"
blue = "#B3AB8E"
magenta = "#C6BB9A"
cyan = "#D5C8A4"
white = "#c3c4c4"

[colors.bright]
black = "#5a646f"
red = "#8F8B75"
green = "#A0997E"
yellow = "#A09B83"
blue = "#B3AB8E"
magenta = "#C6BB9A"
cyan = "#D5C8A4"
white = "#c3c4c4"

[colors.dim]
black = "#c3c4c4"
red = "#8F8B75"
green = "#C6BB9A"
yellow = "#A09B83"
blue = "#B3AB8E"
magenta = "#A0997E"
cyan = "#D5C8A4"
white = "#5a646f"

