--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/archy/github/wallpapers/CherryBlossom.png"

-- Special
background="#110b07"
foreground="#c3c2c1"
cursor="#c3c2c1"

-- Colors
color0="#110b07"
color1="#B6A48A"
color2="#D4B495"
color3="#D8CDAD"
color4="#E0CFAC"
color5="#E7D5B6"
color6="#E9DDC3"
color7="#c3c2c1"
color8="#6a5f56"
color9="#B6A48A"
color10="#D4B495"
color11="#D8CDAD"
color12="#E0CFAC"
color13="#E7D5B6"
color14="#E9DDC3"
color15="#c3c2c1"
