# Shell variables
# Generated by 'wal'
wallpaper="/home/archy/github/wallpapers/CherryBlossom.png"

# Special
background='#110b07'
foreground='#c3c2c1'
cursor='#c3c2c1'

# Colors
color0='#110b07'
color1='#B6A48A'
color2='#D4B495'
color3='#D8CDAD'
color4='#E0CFAC'
color5='#E7D5B6'
color6='#E9DDC3'
color7='#c3c2c1'
color8='#6a5f56'
color9='#B6A48A'
color10='#D4B495'
color11='#D8CDAD'
color12='#E0CFAC'
color13='#E7D5B6'
color14='#E9DDC3'
color15='#c3c2c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
