[colors]
background = '#110b078e'
black = '#110b07'
blue = '#B6A48A'
cursor = '#c3c2c1'
cyan = '#D4B495'
foreground = '#c3c2c1'
green = '#D8CDAD'
magenta = '#E0CFAC'
red = '#E7D5B6'
tabs = '#c3c2c1'
tabs-active = '#E9DDC3'
white = '#c3c2c1'
yellow = '#c3c2c1'
dim-black = '#110b078e'
dim-blue = '#B6A48A8e'
dim-cyan = '#D4B4958e'
dim-foreground = '#c3c2c18e'
dim-green = '#D8CDAD8e'
dim-magenta = '#E0CFAC8e'
dim-red = '#E7D5B68e'
dim-white = '#E9DDC38e'
dim-yellow = '#c3c2c18e'
light-black = '#B6A48A'
light-blue = '#D4B495'
light-cyan = '#D8CDAD'
light-foreground = '#E0CFAC'
light-green = '#E7D5B6'
light-magenta = '#E9DDC3'
light-red = '#c3c2c1'
light-white = '#B6A48A'
light-yellow = '#D4B495'
