[colors.primary]
background = "#110b07"
foreground = "#c3c2c1"

[colors.cursor]
text = "#110b07"
cursor = "#c3c2c1"

[colors.vi_mode_cursor]
text = "#110b07"
cursor = "#c3c2c1"

[colors.search.matches]
foreground = "#110b07"
background = "#c3c2c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a5f56"
background = "#c3c2c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#110b07"
red = "#B6A48A"
green = "#D4B495"
yellow = "#D8CDAD"
blue = "#E0CFAC"
magenta = "#E7D5B6"
cyan = "#E9DDC3"
white = "#c3c2c1"

[colors.bright]
black = "#6a5f56"
red = "#B6A48A"
green = "#D4B495"
yellow = "#D8CDAD"
blue = "#E0CFAC"
magenta = "#E7D5B6"
cyan = "#E9DDC3"
white = "#c3c2c1"

[colors.dim]
black = "#c3c2c1"
red = "#B6A48A"
green = "#E7D5B6"
yellow = "#D8CDAD"
blue = "#E0CFAC"
magenta = "#D4B495"
cyan = "#E9DDC3"
white = "#6a5f56"

